sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: p9/Ks6a9Bsk+gZEnMDk0nw2OFGhY+9phqpWqEFv4iPtqW8E41Bj2D3yJYTGrQF1f0mS7mqW02+9zB++maLC/Xb+PqbW/5x6jm+VTT9bnGm2DM8xban8v52/Z0EhrV3By0e525AxaNekZw1gUsQHiJpHgdECyZTuPAtpVFPD+WEj2huEHMoElJDRkjStWrLV6uDfc4evo/KsaI2QLrdCyoejR8Z3k1qc51FGusY+B1AbJG0i4GuBDQEB4gu5LzZ30e7Q4T8Av3tfUuNEZja08oMOesXstOhfpYJ7X74TagpBmtgLJBju3DXxTEOQKyuoWNMfnNYv6x150S2EFYoiffkbB35Qfh0hIVbQ0aAs7w+QCvBFynKzNq3ADp79+z3s1rjI2tHtOj93P4XEjVJqYiGRuRjD3oC5KbkTGXmG2FzhGAGRoB84zvgPh0LqDBfBdBZoj584doETornZ7GJWkzYhhDxkiUwT7p9B3pElXwOAd0QiM0uTg0ruPfWVgnbvgFzSNK/qb22qXvEzy9hzD48jPiMhrlenkUq4NQtpXjyBPvAXQqErd60SLXWR1j0PTh7a2EahhjMLCqmrKM86x1HFkQLu5q2sKN95NM/6ltGioCZe9rUB+Pe/i+ls0/31YC+LxGPu7jBkb9/bDf2gSAfB3KoEgmaak/+wrIaDBbek=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Their-Pilgrimage_3102
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy